server:
  port: 8088

spring:
  data:
    mongodb:
      authentication-database: admin
      database: vending-machine
      username: root
      password: secret123
      host: localhost
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration